version: '3.6'
services:
  mongo:
    image: mongo:4.0.6-xenial
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: exampl
    networks:
      - backendmesh
    tty: true

  node:
    context: ./node
    restart: on-failure
    networks:
      - backendmesh
    tty: true

  envoy:
    context: ./envoy
    restart: on-failure
    expose:
      - 80:80
      - 443:443
    networks:
      - backendmesh
    command: /usr/local/bin/envoy -c /etc/envoy.yaml
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy.yaml
    tty: true

  front:
    context: ./nginx
    restart: on-failure
    networks:
      - backendmesh
    volumes:
      # - ~/nginx_certs:/etc/nginx/certs
      # - ~/letsencrypt_www:/var/www/letsencrypt
      - ~/app:/var/www
      - ~/app-logs/nginx:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
    tty: true

volumes:
  data:
    driver: local

networks:
  backendmesh: {}
